<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice {{ $fee->receipt_number }}</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; margin: 0; padding: 28px; }
        .header { border-bottom: 3px solid #1d4ed8; padding-bottom: 16px; margin-bottom: 20px; }
        .brand { font-size: 22px; font-weight: bold; color: #1d4ed8; margin: 0 0 4px; }
        .subtitle { color: #6b7280; margin: 0; }
        .meta { width: 100%; margin-bottom: 18px; }
        .meta td { vertical-align: top; width: 50%; padding: 0; }
        .label { color: #6b7280; font-size: 10px; text-transform: uppercase; margin-bottom: 2px; }
        .value { font-weight: bold; margin: 0 0 8px; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 12px; }
        table.items th { background: #111827; color: #fff; text-align: left; padding: 8px 10px; font-size: 10px; text-transform: uppercase; }
        table.items td { border: 1px solid #e5e7eb; padding: 10px; }
        .totals { width: 280px; margin-left: auto; margin-top: 16px; border-collapse: collapse; }
        .totals td { padding: 6px 0; }
        .totals .grand { font-size: 16px; font-weight: bold; }
        .paid { color: #047857; font-weight: bold; }
        .due { color: #b45309; font-weight: bold; }
        .footer { margin-top: 28px; color: #6b7280; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <p class="brand">{{ $business->name }}</p>
        <p class="subtitle">{{ $business->address }} @if($business->phone) · {{ $business->phone }} @endif @if($business->email) · {{ $business->email }} @endif</p>
    </div>

    <table class="meta">
        <tr>
            <td>
                <div class="label">From</div>
                <p class="value">{{ $business->name }}</p>
                <div class="label">Bill to</div>
                <p class="value">{{ $parent?->full_name ?? $childName }}</p>
                <p>Child: {{ $childName }}</p>
                <p>{{ $idLabel }}: {{ $idValue ?: '—' }}</p>
            </td>
            <td>
                <div class="label">Invoice</div>
                <p class="value">{{ $fee->receipt_number ?: ('FEE-'.$fee->id) }}</p>
                <p>Date: {{ optional($fee->payment_date)->format('d M Y') ?: now()->format('d M Y') }}</p>
                <p>Due: {{ optional($fee->due_date)->format('d M Y') ?: '—' }}</p>
                <p>Status: <span class="{{ $fee->remainingBalance() > 0 ? 'due' : 'paid' }}">{{ strtoupper($fee->payment_status) }}</span></p>
            </td>
        </tr>
    </table>

    <table class="items">
        <thead>
            <tr>
                <th>Description</th>
                <th>Term</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $fee->fee_type }}</td>
                <td>{{ $termLabel ?: '—' }}</td>
                <td>UGX {{ number_format((float) $fee->amount, 0) }}</td>
            </tr>
            @foreach($fee->payments as $payment)
                <tr>
                    <td>Payment · {{ $payment->methodLabel() }} @if($payment->receipt_number) ({{ $payment->receipt_number }}) @endif</td>
                    <td>{{ optional($payment->paid_at)->format('d M Y') }}</td>
                    <td>- UGX {{ number_format((float) $payment->amount, 0) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <table class="totals">
        <tr>
            <td>Billed</td>
            <td style="text-align:right">UGX {{ number_format((float) $fee->amount, 0) }}</td>
        </tr>
        <tr>
            <td>Paid</td>
            <td style="text-align:right" class="paid">UGX {{ number_format((float) $fee->amount_paid, 0) }}</td>
        </tr>
        <tr class="grand">
            <td>{{ $fee->credit() > 0 ? 'Credit' : 'Balance due' }}</td>
            <td style="text-align:right">UGX {{ number_format(abs($fee->remainingBalance()), 0) }}</td>
        </tr>
    </table>

    <p class="footer">
        <strong>Terms &amp; conditions.</strong>
        Payment is due by {{ optional($fee->due_date)->format('d M Y') ?: 'the due date shown above' }}.
        Keep this invoice for your records.
        Generated by Quisat for {{ $business->name }}.
    </p>
</body>
</html>
